CREATE TABLE IF NOT EXISTS Product (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    CategoryId INT NOT NULL,
    SellingPrice DECIMAL(10,2) NOT NULL,
    Quantity INT NOT NULL DEFAULT 0,
    Unit ENUM('Piece', 'Package') NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Product_Category FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);